import { Movies } from "../types/moviesList"
export class DataFile {
    static movie : Movies[] =  [
        {
          name : "Black Adam",
          pg : "PG-13",
          year : 2022,
         genre : "Action | Superhero",
        time : "2h 4m",
        disc : "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods-and imprisoned just as quickly-Black Adam (Johnson) is freed from ...",
        imdbTitle : "https://www.imdb.com/title/tt6443346/",
        imgsrc : "https://i0.wp.com/batman-news.com/wp-content/uploads/2022/09/Black-Adam-Character-Poster-Black-Adam-01.jpg?fit=2764%2C4096&quality=80&strip=info&ssl=1",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=mkomfZHG5q4",
        rating : "--",
        showTime : "12:30pm"
        },
        {
          name : "Wonder Woman 1984",
          pg : "PG-13",
          year : 2020,
         genre : "Action | Fantasy",
        time : "2h 31m",
        disc : "Diana must contend with a work colleague and businessman, whose desire for extreme wealth sends the world down a path of destruction, after an ancient artifact that grants wishes goes missing.",
        imdbTitle : "https://www.imdb.com/title/tt7126948/",
        imgsrc : "https://collider.com/wp-content/uploads/2020/12/wonder-woman-1984-character-poster-december-gal-gadot.jpeg",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=sfM7_JLk-84",
        rating : "2.3/5",
        showTime:"3:00pm"
        },
        {
          name : "Sita Ramam",
          pg : "PG-13",
          year : 2022,
         genre : "Drama | Mystery",
        time : "2h 43m",
        disc : "An orphan soldier, Lieutenant Ram's life changes, after he gets a letter from a girl named Sita. He meets her and love blossoms between them. When he ...",
        imdbTitle : "https://www.imdb.com/title/tt20850406/",
        imgsrc : "https://dvvy6louqcr7j.cloudfront.net/vista/HO00013763/heroPoster/Sita-Ramam.png",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=Ljk6tGZ1l3A",
        rating : "4.5/5",
        showTime:"6:00pm"
        },
        {
          name : "Ponniyin Selvan 1",
          pg : "PG-13",
          year : 2022,
         genre : "Action | Drama",
        time : "2h 4m",
        disc : "Vandiyathevan sets out to cross the Chola land to deliver a message from the Crown Prince Aditha Karikalan. Kundavai attempts to establish political peace as vassals and petty chieftains plot against the throne. Unrest grips the land as a long-tailed comet arrives, signalling a time of turmoil.",
        imdbTitle : "https://www.imdb.com/title/tt10701074/",
        imgsrc : "https://pbs.twimg.com/media/E6p_cZgVUAAT_4z?format=jpg&name=900x900",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=D4qAQYlgZQs",
        rating : "4.1/5",
        showTime : "4:30pm"
        },
        {
        name : "Karthikeya 2",
        pg : "PG-13",
        year : 2022,
        genre : "Thriller | Fantasy",
        time : "2h 30m",
        disc : "A sequel to mystic thriller Karthikeya, which deals with the personal problems of Karthik and how he comes out of them. His pursuit of the truth leads him to find out the power of Indian ancient system and Tatva of Lord Sri Krishna.",
        imdbTitle : "https://www.imdb.com/title/tt13664684/",
        imgsrc : "https://www.filmibeat.com/fanimg/movie/13189/karthikeya-2-photos-images-78500.jpg",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=d5s_IGuOJEc",
        rating : "3.9/5",
        showTime:"2:30pm"
        },
        {
          name : "Black Panther 2",
          pg : "PG-13",
          year : 2022,
         genre : "Action | Adventure",
        time : "2h 41m",
        disc : "The nation of Wakanda is pitted against intervening world powers as they mourn the loss of their king T'Challa.",
        imdbTitle : "https://www.imdb.com/title/tt9114286/?ref_=ttls_li_tt",
        imgsrc : "https://m.media-amazon.com/images/M/MV5BNTM4NjIxNmEtYWE5NS00NDczLTkyNWQtYThhNmQyZGQzMjM0XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=Ljk6tGZ1l3A",
        rating : "--",
        showTime:"10:30am"
        },
        {
          name : "Vikram Vedha",
          pg : "PG-13",
          year : 2022,
         genre : "Crime | Thriller",
        time : "2h 40m",
        disc : "A tough police officer sets out to track down and kill an equally tough gangster.",
        imdbTitle : "https://www.imdb.com/title/tt13131350/",
        imgsrc : "https://m.media-amazon.com/images/M/MV5BYTEyYjgzNmUtM2QyYi00MWMwLWExMDctZmY1NmZhNGY5MWNiXkEyXkFqcGdeQXVyOTcwMTQxMTM@._V1_.jpg",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=hpwnlr-ZHB0",
        rating : "3.3/5",
        showTime : "12:30pm"
        },
        {
          name : "Top Gun : Maverick",
          pg : "PG-13",
          year : 2020,
         genre : "Action | Drama",
        time : "2h 10m",
        disc : "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.",
        imdbTitle : "https://www.imdb.com/title/tt1745960/",
        imgsrc : "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=qSqVVswa420",
        rating : "4.2/5",
        showTime:"1:00pm"
        },
        {
          name : "One Piece Film : Red",
          pg : "U",
          year : 2022,
         genre : "Anime | Adventure",
        time : "1h 55m",
        disc : "For the first time ever, Uta - the most beloved singer in the world - will reveal herself to the world at a live concert. The voice that the whole world has been waiting for is about to resound.",
        imdbTitle : "https://www.imdb.com/title/tt16183464/?ref_=nv_sr_srsg_0",
        imgsrc : "https://m.media-amazon.com/images/M/MV5BZjY1MzBmNTgtMTYwZS00ODE0LWE1NDItNmJjNzYxNDEyY2YwXkEyXkFqcGdeQXVyNjM0MTI4Mw@@._V1_.jpg",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=89JWRYEIG-s",
        rating : "2.9/5",
        showTime:"8:00pm"
        },
        {
          name : "Black Adam",
          pg : "PG-13",
          year : 2022,
         genre : "Action | Superhero",
        time : "2h 4m",
        disc : "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods-and imprisoned just as quickly-Black Adam (Johnson) is freed from ...",
        imdbTitle : "https://www.imdb.com/title/tt6443346/",
        imgsrc : "https://i0.wp.com/batman-news.com/wp-content/uploads/2022/09/Black-Adam-Character-Poster-Black-Adam-01.jpg?fit=2764%2C4096&quality=80&strip=info&ssl=1",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=mkomfZHG5q4",
        rating : "--",
        showTime : "12:30pm"
        },
        {
          name : "Wonder Woman 1984",
          pg : "PG-13",
          year : 2020,
         genre : "Action | Fantasy",
        time : "2h 31m",
        disc : "Diana must contend with a work colleague and businessman, whose desire for extreme wealth sends the world down a path of destruction, after an ancient artifact that grants wishes goes missing.",
        imdbTitle : "https://www.imdb.com/title/tt7126948/",
        imgsrc : "https://collider.com/wp-content/uploads/2020/12/wonder-woman-1984-character-poster-december-gal-gadot.jpeg",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=sfM7_JLk-84",
        rating : "2.3/5",
        showTime:"3:00pm"
        },
        {
          name : "Sita Ramam",
          pg : "PG-13",
          year : 2022,
         genre : "Drama | Mystery",
        time : "2h 43m",
        disc : "An orphan soldier, Lieutenant Ram's life changes, after he gets a letter from a girl named Sita. He meets her and love blossoms between them. When he ...",
        imdbTitle : "https://www.imdb.com/title/tt20850406/",
        imgsrc : "https://dvvy6louqcr7j.cloudfront.net/vista/HO00013763/heroPoster/Sita-Ramam.png",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=Ljk6tGZ1l3A",
        rating : "4.5/5",
        showTime:"6:00pm"
        },
        {
          name : "Black Adam",
          pg : "PG-13",
          year : 2022,
         genre : "Action | Superhero",
        time : "2h 4m",
        disc : "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods-and imprisoned just as quickly-Black Adam (Johnson) is freed from ...",
        imdbTitle : "https://www.imdb.com/title/tt6443346/",
        imgsrc : "https://i0.wp.com/batman-news.com/wp-content/uploads/2022/09/Black-Adam-Character-Poster-Black-Adam-01.jpg?fit=2764%2C4096&quality=80&strip=info&ssl=1",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=mkomfZHG5q4",
        rating : "--",
        showTime : "12:30pm"
        },
        {
          name : "Wonder Woman 1984",
          pg : "PG-13",
          year : 2020,
         genre : "Action | Fantasy",
        time : "2h 31m",
        disc : "Diana must contend with a work colleague and businessman, whose desire for extreme wealth sends the world down a path of destruction, after an ancient artifact that grants wishes goes missing.",
        imdbTitle : "https://www.imdb.com/title/tt7126948/",
        imgsrc : "https://collider.com/wp-content/uploads/2020/12/wonder-woman-1984-character-poster-december-gal-gadot.jpeg",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=sfM7_JLk-84",
        rating : "2.3/5",
        showTime:"3:00pm"
        },
        {
          name : "Sita Ramam",
          pg : "PG-13",
          year : 2022,
         genre : "Drama | Mystery",
        time : "2h 43m",
        disc : "An orphan soldier, Lieutenant Ram's life changes, after he gets a letter from a girl named Sita. He meets her and love blossoms between them. When he ...",
        imdbTitle : "https://www.imdb.com/title/tt20850406/",
        imgsrc : "https://dvvy6louqcr7j.cloudfront.net/vista/HO00013763/heroPoster/Sita-Ramam.png",
        tickets : 100,
        trailer : "https://www.youtube.com/watch?v=Ljk6tGZ1l3A",
        rating : "4.5/5",
        showTime:"6:00pm"
        }
      ]

      
  static data: Movies[] = this.movie;
  
}

